---
name: 🤖 Issue/PR Automation
on:
  pull_request:
  issues:
    types: [opened]

permissions: {}

jobs:
  labeler:
    name: 🏷️ Labeler
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: 🏷️ Apply label on PR
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
